language: node_js
sudo: required
node_js:
- '8'
jobs:
  include:
  - stage: test
    if: NOT branch = master
    services:
    - mongodb
    cache:
      yarn: true
      directories:
      - node_modules
    before_install:
    - openssl aes-256-cbc -K $encrypted_2f6d61fcabf9_key -iv $encrypted_2f6d61fcabf9_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - chmod +x scripts/choose_firebase_config.sh
    - scripts/choose_firebase_config.sh
    script:
    - yarn lint
    - yarn test:unit --ci --forceExit
    - yarn test:client
  - stage: deploy
    if: branch =~ /(master|next)/
    install:
    - yarn
    cache:
      yarn: true
      directories:
      - node_modules
    before_install:
    - openssl aes-256-cbc -K $encrypted_2f6d61fcabf9_key -iv $encrypted_2f6d61fcabf9_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - chmod +x scripts/choose_firebase_config.sh
    - scripts/choose_firebase_config.sh
    script:
    - yarn docs
    - yarn build:client
    deploy:
    - provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      local_dir: docs/
    - provider: firebase
      skip_cleanup: true
      token:
        secure: ecDRfSeLDIhqwPP2MAkBNyrkMjHtJqMOK3/b03rNk9kVoyROLSSIci6xzBN2xi6rNv1X3JcPje9gRrfv/NPLOFeH+gX3aBO7KoNl5sjT6ZdiI2n+xnXjlbP8R8a1FIPt/JF0/+a19Ybzuaz6EPnCw+nnn8IXejYnjOG9BB2mD28Ms98yQs9c0YTXCCLCJ06Kzr284pP6WpK7ZA2UvWi2HJHwXUgtuxjDTCNcQ1nuX8SD1DlyCmtP4Tboxj3hLZ8mhgNvpYJ+WMPmuiB8d8p6HbLVMaDRDJvvDVhnA2hWrUr4Ggoi7GhiIwiM8jVM7AlxUA40MlObrMZUu0SAy/7a5dJs8V/AjJNuciYHnH1C78m+P0Dz4l8MNrD7GLIF6aodEkVSEyte/n9I9VVpzBvEz+XIxUHTpC4xUbet/Pir+2WmxdCjdeQE9/mpmi/fs/I8AwbcRwqFdcph03v0pp3wBBGE2AZ6ylxRtjzwUykz3MzeWeNe/pMcMPvAM1p+85q59MNBQ6k3fBvIY0qOpp6mBswVw52tr40o2+/Fovew1x0Ctnh/nhJEMC+/6vWOPVG73y4BBPA1X+zTI6S6PrubkaQOf4u4k6IcJ8SRq3RTifX9Dibzvffzk7sRVfSf3ryo+nc5cc0nfB3YXWx89yX4EwkwE8jEoD8Ag6RpYunKmRU=
      project: acm-texas-tech-web-app-2
      message: Deployed to production
      on:
        branch: master
    - provider: firebase
      skip_cleanup: true
      token:
        secure: ecDRfSeLDIhqwPP2MAkBNyrkMjHtJqMOK3/b03rNk9kVoyROLSSIci6xzBN2xi6rNv1X3JcPje9gRrfv/NPLOFeH+gX3aBO7KoNl5sjT6ZdiI2n+xnXjlbP8R8a1FIPt/JF0/+a19Ybzuaz6EPnCw+nnn8IXejYnjOG9BB2mD28Ms98yQs9c0YTXCCLCJ06Kzr284pP6WpK7ZA2UvWi2HJHwXUgtuxjDTCNcQ1nuX8SD1DlyCmtP4Tboxj3hLZ8mhgNvpYJ+WMPmuiB8d8p6HbLVMaDRDJvvDVhnA2hWrUr4Ggoi7GhiIwiM8jVM7AlxUA40MlObrMZUu0SAy/7a5dJs8V/AjJNuciYHnH1C78m+P0Dz4l8MNrD7GLIF6aodEkVSEyte/n9I9VVpzBvEz+XIxUHTpC4xUbet/Pir+2WmxdCjdeQE9/mpmi/fs/I8AwbcRwqFdcph03v0pp3wBBGE2AZ6ylxRtjzwUykz3MzeWeNe/pMcMPvAM1p+85q59MNBQ6k3fBvIY0qOpp6mBswVw52tr40o2+/Fovew1x0Ctnh/nhJEMC+/6vWOPVG73y4BBPA1X+zTI6S6PrubkaQOf4u4k6IcJ8SRq3RTifX9Dibzvffzk7sRVfSf3ryo+nc5cc0nfB3YXWx89yX4EwkwE8jEoD8Ag6RpYunKmRU=
      project: acm-texas-tech-web-app-2-beta
      message: Deployed to staging
      on:
        branch: next
  - stage: acceptance
    if: branch = next
    cache:
      yarn: true
      directories:
      - node_modules
    install:
    - yarn
    - yarn run cypress install
    script:
    - yarn e2e:ci
notifications:
  email: false
