language: node_js
node_js:
- '8'
jobs:
  include:
  - stage: test
    services:
    - mongodb
    cache:
      yarn: true
      directories:
      - node_modules
    script:
    - yarn lint
    - yarn test:ci --ci --forceExit --detectOpenHandles --maxWorkers=10
  - stage: deploy
    install:
    - npm install -g firebase-tools@latest
    - yarn add -DE esdoc@0.5.2 esdoc-node@1.0.2
    script:
    - yarn docs
    deploy:
    - provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      local_dir: docs/
      on:
        branch: master
    - provider: firebase
      skip_cleanup: true
      token:
        secure: "KYW9YprJXXfV75L2q3qwzhDtYO1h5uiYjZgxylwzcNn5QWwcLRiWhlobv/U42PBDP5S4ngi4SRDfwzYlmY/ix2NCLiCC4RHQbcchWXfGa3ukusU1bjqyVOWBwDp1APlVS5DGv209JiVVu02UeRNlcSRmlAK076HfSKYVVHFilkfv0o5JEu0fLmozQKTZ/4ahU1LV9Re9/edOFdzURlYN4LxN3HQxv6rka2RlYhn2NtvQOQPY99+A77i2mC3BGTMGLxxB31oYjqbisgoKUVAeAWW/L5gsTaUuaoW7Ynrfumyq0WzxX/hH4/IXFG/tXLLJqMPyIRyXsNRJmVmox9sLG+MindVTQQfWyimq1953Blvu869Sn/aE1MAjsDBAPO9I08aErc9asBBuzpIrSO2jnD1pyxJ7o1gjE5ZU/lGhk4xeHjHxLf5H6GyZ965EjT8q2kx5qwHXa96HntuXnX2UafLqpe9f8ao4HD/8ibXsF6zBRaQ8IV9a2TAlpCYrskCU2C8SeY9/4rpdanFbr3DVkqIx6OPtX0+jhbs6mTifzG6VBG7TGy7z0tKokpavZYVjLjb7EgZplNnGwbNSTdBRq/RcZrmUqcHeT4t7x4YQarvhUIqoJT/T0+300ggYElqb6De+N/nXDLJJ0wTjsWcKE9n1cxdPtnMu3EPosMGo3xk="
      project: acm-texas-tech-web-app-2
      message: Deployed to production
      on:
        branch: master
    - provider: firebase
      skip_cleanup: true
      token:
        secure: "KYW9YprJXXfV75L2q3qwzhDtYO1h5uiYjZgxylwzcNn5QWwcLRiWhlobv/U42PBDP5S4ngi4SRDfwzYlmY/ix2NCLiCC4RHQbcchWXfGa3ukusU1bjqyVOWBwDp1APlVS5DGv209JiVVu02UeRNlcSRmlAK076HfSKYVVHFilkfv0o5JEu0fLmozQKTZ/4ahU1LV9Re9/edOFdzURlYN4LxN3HQxv6rka2RlYhn2NtvQOQPY99+A77i2mC3BGTMGLxxB31oYjqbisgoKUVAeAWW/L5gsTaUuaoW7Ynrfumyq0WzxX/hH4/IXFG/tXLLJqMPyIRyXsNRJmVmox9sLG+MindVTQQfWyimq1953Blvu869Sn/aE1MAjsDBAPO9I08aErc9asBBuzpIrSO2jnD1pyxJ7o1gjE5ZU/lGhk4xeHjHxLf5H6GyZ965EjT8q2kx5qwHXa96HntuXnX2UafLqpe9f8ao4HD/8ibXsF6zBRaQ8IV9a2TAlpCYrskCU2C8SeY9/4rpdanFbr3DVkqIx6OPtX0+jhbs6mTifzG6VBG7TGy7z0tKokpavZYVjLjb7EgZplNnGwbNSTdBRq/RcZrmUqcHeT4t7x4YQarvhUIqoJT/T0+300ggYElqb6De+N/nXDLJJ0wTjsWcKE9n1cxdPtnMu3EPosMGo3xk="
      project: acm-texas-tech-web-app-2-beta
      message: Deployed to staging
      on:
        branch: next

notifications:
  email: false
