version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
      - image: circleci/mongo:3

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: openssl enc -aes-256-cbc -K $KEY -iv $KEY -in secrets.tar.enc -out secrets.tar -d
      - run: tar xvf secrets.tar
      - run: chmod +x scripts/choose_firebase_config.sh
      - run: scripts/choose_firebase_config.sh

      # Lint and Test
      - run: yarn lint
      - run: yarn test:unit --ci --forceExit
      - run: yarn test:client
